version: '3.8'

services:
  server:
    build: ./server
    env_file: .env
    expose: ["3000"]
    dns:
    - 8.8.8.8
    - 1.1.1.1

  frontend:
    build: ./order-react-app
    expose: ["80"]
    dns:
    - 8.8.8.8
    - 1.1.1.1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/certs:/etc/letsencrypt
      # - ./acme-challenge:/var/www/challenge
      - ./nginx/certs:/etc/nginx/certs
      - ./acme-challenge:/var/www/challenge